CREATE TABLE IF NOT EXISTS groups (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,

  group_name VARCHAR(255) NOT NULL,
  group_type VARCHAR(100) NOT NULL,
  parent_group VARCHAR(255),
  description TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);